### ISSUE TITLE
Add PHPMyAdmin to all projects

### ISSUE THREAD

**Issue by jblechinger** [ddev/ddev-phpmyadmin#5]
Would be great to have this extension added to all projects by default like it was before. 
Is there any global option that im missing? 

Its a bit painfull to always install myadmin and then restart ddev to make it work again.

Thanks

**Comment by jblechinger** [comment]
Oh im on macOs btw. My colleague on windows said its working ootb for him

**Comment by rfay** [comment]
No, there is not a global option.

And no, with v1.22 phpmyadmin is not available by default on Windows or macOS. 

All you need to do is a one-time `ddev get ddev/ddev-phpmyadmin` and check in the results and all your team members will have it on that project.

**Comment by rfay** [comment]
Closing, I don't expect this to be possible in the future

**Comment by loeffe1** [comment]
Why can't we add this to the post-start hook?

**Comment by stasadev** [comment]
@loeffe1,

This is a *one-time* action `ddev get ddev/ddev-phpmyadmin`, after installing the add-on you can commit the changes to the `.ddev` folder and always have the add-on in your project.

Of course, you need to repeat this *one-time* action in all projects that you want to use with PHPMyAdmin.

**Comment by ChloeSartorelli** [comment]
This should probably be closed.
There might be a use case for a global config like `default_addons` or similar to add some add-ons by default to all new projects - but that would be a `ddev/ddev` thing.

The specific change this issue requests isn't suitable, because this is one of several optional add-ons that do similar things. Developers who want adminer for example shouldn't have phpmyadmin added to their projects for example.

**Comment by rfay** [comment]
We won't be adding the requested feature. It looks like I tried to close and pushed the wrong button.

If you want to install ddev/ddev-phpmyadmin on all listed projects:
```
for item in $(ddev list -j |  docker run -i --rm ddev/ddev-utilities jq -r .raw[].approot); do cd $item; ddev get ddev/ddev-phpmyadmin; done
```
