### ISSUE TITLE
Support multiple databases

### ISSUE THREAD

**Issue by StryKaizer** [ddev/ddev-phpmyadmin#6]
In the past multiple databases were automaticly supported.

Now, when doing "ddev get ddev/ddev-phpmyadmin", only the "db" is exposed.

A manual fix is altering docker-compose.phpmyadmin.yaml
- remove PMA_HOST line
- add instead (comma seperated): 
   PMA_HOSTS=db,yourotherdatabasename

I think you should either document how to do this manually or automaticly detect all available databases and expose them (if this is possible)?

**Comment by rfay** [comment]
Thanks, I agree that it should show all databases. 

Here's the relevant section from the previous setup (DDEV v1.21.6): https://github.com/ddev/ddev/blob/1748e9a27948b190308ffd130da1ab5650ca0e7a/pkg/ddevapp/app_compose_template.yaml#L262-L270

What's the difference? 

We don't want PMA_HOSTS I don't think; all databases are on the same host (`db`). It seems the problem is something else. 

Here's the current: 

https://github.com/ddev/ddev-phpmyadmin/blob/e9a3c79fc868ceed0942f5d977e60306e82e1de9/docker-compose.phpmyadmin.yaml#L13-L21

I'm not sure I see the difference. The key thing would be the username used (`root`) and both are the same.

**Comment by rfay** [comment]
I'm not seeing the problem you're reporting. I created a second database using `ddev import-db -d seconddb --file=.tarballs/db.sql` and it shows just fine, exactly the same as it would have previously.

<img width="370" alt="image" src="https://github.com/ddev/ddev-phpmyadmin/assets/112444/ca2fa1d3-0e81-4580-88d7-a72974d7edb4">

**Comment by StryKaizer** [comment]
I tested again, and this time it shows up.
Not sure what went wrong first time I tried, but since I cant reproduce it anymore, closing. Sorry and thanks for the quick response!!
